services:
  - type: web
    name: setlist-playlist-generator
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SPOTIFY_CLIENT_ID
        value: 95e68bd6da33466c960d4a0a76323837
      - key: SPOTIFY_CLIENT_SECRET
        value: 792689bec07f49f3ae926747338442d4
      - key: SETLISTFM_API_KEY
        value: fAfNdnOQbmUXQ-8DEcsKLeOEyvJRmkpQ5AlD
      - key: APPLE_MUSIC_TEAM_ID
        value: 9Z629B5YHG
      - key: APPLE_MUSIC_KEY_ID
        value: CL75Y83769

  - type: web
    name: setlist-playlist-generator-site
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
